#page title
page_title: UserAgent Switcher # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 6746084006 # Required. Enter iOS app ID to automatically populate name, price and icon (e.g. 718043190).
ios_app_country: jp # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link:
# Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
# Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: PC版/スマホ版Webブラウザの切り替えが簡単

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: A.Suzuki
your_link:
your_city: Tokyo
email_address: kyotohan70th@gmail.com
facebook_username:
instagram_username:
twitter_username:
github_username:
youtube_username:
mastodon_link:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: シンプルなUI
    description: 直感的で使いやすいインターフェースを採用。誰でも簡単に操作可能。
    fontawesome_icon_name: magic

  - title: UserAgent切り替え機能
    description: PC版Webサイトとスマホ版Webサイトを簡単に切り替えできます。
    fontawesome_icon_name: mobile

  - title: ブックマーク機能
    description: お気に入りのWebページをブックマークとして保存できます。。
    fontawesome_icon_name: edit

  - title: 履歴機能
    description: 一般的なブラウザ同様に閲覧ページを履歴として保存できます。
    fontawesome_icon_name: trash-alt

  - title: ブラウザ機能
    description: 基本的なブラウザに搭載される機能を持ちます。
    fontawesome_icon_name: adjust

  - title: 多言語対応
    description: 日本語、英語、中国語をはじめ多言語に対応したアプリです。
    fontawesome_icon_name: globe

  - title: Coming Soon...
    description: さらなる機能が続々追加予定です。次回のアップデートをお楽しみに！
    fontawesome_icon_name: arrow-alt-circle-down

  - title: Coming Soon...
    description: さらなる機能が続々追加予定です。次回のアップデートをお楽しみに！
    fontawesome_icon_name: arrow-alt-circle-down

  - title: Coming Soon...
    description: さらなる機能が続々追加予定です。次回のアップデートをお楽しみに！
    fontawesome_icon_name: arrow-alt-circle-down

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
